# Generated by Django 4.2.3 on 2023-09-22 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "001_migration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Categories",
        ),
    ]
