# Generated by Django 4.2.3 on 2023-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0002_delete_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
