# Generated by Django 4.2.3 on 2023-09-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "003_news_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.users"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(to="news.categories"),
        ),
    ]
