# Generated by Django 4.2.3 on 2023-09-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="name",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
