# Generated by Django 4.2.3 on 2023-09-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_categories_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
